/**
 * In-memory web session store.
 * Keyed by sessionId (generated by the frontend, persisted in localStorage).
 * Mirrors the Grammy session used by the Telegram bot but uses plain objects.
 */

export type WebFsmState =
  | 'candidate_asking'
  | 'consent'
  | 'data_collection'
  | 'file_upload'
  | 'scoring'
  | 'pass'
  | 'fail'
  | 'interview_completed'
  | 'escalated'

export interface WebJobListing {
  title: string
  location: string
  company?: string
  requirements?: string
  salary?: string
}

export interface WebSession {
  sessionId: string
  state: WebFsmState
  appliedJob: string | null
  appliedJobLocation: string | null
  consentRecordedAt: string | null
  currentQuestionIndex: number
  currentUploadPage: number
  answers: Record<string, string>      // questionNumber → answer / file URL
  lastShownJobs: WebJobListing[]
  pendingApplyJob: WebJobListing | null
  createdAt: number
  updatedAt: number
}

const SESSION_TTL_MS = 4 * 60 * 60 * 1000  // 4 hours

const store = new Map<string, WebSession>()

// Prune expired sessions every hour
setInterval(() => {
  const cutoff = Date.now() - SESSION_TTL_MS
  for (const [id, s] of store) {
    if (s.updatedAt < cutoff) store.delete(id)
  }
}, 60 * 60 * 1000)

export function getOrCreateSession(sessionId: string): WebSession {
  let s = store.get(sessionId)
  if (!s) {
    s = {
      sessionId,
      state: 'candidate_asking',
      appliedJob: null,
      appliedJobLocation: null,
      consentRecordedAt: null,
      currentQuestionIndex: 0,
      currentUploadPage: 1,
      answers: {},
      lastShownJobs: [],
      pendingApplyJob: null,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }
    store.set(sessionId, s)
  }
  return s
}

export function saveSession(s: WebSession): void {
  s.updatedAt = Date.now()
  store.set(s.sessionId, s)
}

export function resetSession(sessionId: string): void {
  const s = store.get(sessionId)
  if (!s) return
  s.state = 'candidate_asking'
  s.appliedJob = null
  s.appliedJobLocation = null
  s.consentRecordedAt = null
  s.currentQuestionIndex = 0
  s.currentUploadPage = 1
  s.answers = {}
  s.pendingApplyJob = null
  s.updatedAt = Date.now()
}
